cfg: !!python/object:config.Config
  data_cfg: !!python/object:config.DataConfig
    NON_SPEECH_LABEL: 3
    bs: 10
    clip_length: 10
    test_dataset_path: competition_dataset/test
    train_dataset_path: competition_dataset/train
    val_dataset_path: competition_dataset/val
  train_cfg: !!python/object:config.TrainConfig
    debug: false
    lr: 5.0e-05
    n_val: 1
